# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_taken',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
