# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20160917_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='time_takens',
            new_name='times_taken',
        ),
    ]
